### ISSUE TITLE
[Feature] Customize format number

### ISSUE THREAD

**Issue by danilort** [nortakales/vs-code-qalc#11]
Qalc 0.1.8.

I suggest some changes to the settings.

Remove this:
```
// Turn this on to display commas in results ($1,000,000), or off to hide commas ($1000000)
qalc.output.displayCommas": true,
```
and add these two:
```
qalc.output.decimalSymbol": "."
qalc.output.digitGroupingSymbol": ","

```
Like Windows 10:

![immagine](https://user-images.githubusercontent.com/16148184/147337869-06667d92-aa76-4a92-9233-f26fd8caccc9.png)

# Now

Now I am much more free to choose the I prefer format.

### English format (like qalc.output.displayCommas": true)

```
qalc.output.decimalSymbol": "."
qalc.output.digitGroupingSymbol": ","
```
![immagine](https://user-images.githubusercontent.com/16148184/147338244-775feee2-ded8-44fc-aba4-605dfc4a3101.png)

### English format (like qalc.output.displayCommas": false)

```
qalc.output.decimalSymbol": "."
qalc.output.digitGroupingSymbol": ""    //void string
```
![immagine](https://user-images.githubusercontent.com/16148184/147338255-42c9f20e-117f-4b89-bb38-4a8d05d3e8e3.png)

## Italian format

```
qalc.output.decimalSymbol": ","
qalc.output.digitGroupingSymbol": "."
```
![immagine](https://user-images.githubusercontent.com/16148184/147338266-a4b1cb4f-b477-4e2a-93f6-1c8493093e53.png)

## Other format

```
qalc.output.decimalSymbol": "."
qalc.output.digitGroupingSymbol": " "   //space
```
![immagine](https://user-images.githubusercontent.com/16148184/147338284-1716e4e1-c399-4608-b539-4e12c9eec66d.png)

Thank's for your job!

**Comment by danilort** [comment]
# How to do

### package.json
```
"qalc.output.carattereSeparaGruppiCifre": {
    "title": "Carattere che raggruppa le cifre",
    "type": "string",
    "default": ".",
    "description": ""
},
"qalc.output.carattereSeparaDecimali": {
    "title": "Carattere che separa i decimali",
    "type": "string",
    "default": ",",
    "description": ""
}
```

### settings.js
```
exports.temperatureShortcut = exports.localCurrencyCode = exports.localCurrencySymbol = exports.convertLocalCurrency = exports.upperExponentBound = exports.lowerExponentBound = exports.notation = exports.precision = exports.trimTrailingZeros = exports.displayCommas = exports.enabledLanguages = exports.maxAlignmentColumn = exports.alignResults = exports.resultsColor = exports.getComputedResultsDelimiter = exports.resultsDelimiter = exports.showResultsDelimiter = exports.carattereSeparaGruppiCifre = exports.carattereSeparaDecimali = void 0; 

const SEPARA_GRUPPI_CIFRE = "qalc.output.carattereSeparaGruppiCifre";     //DG
const SEPARA_DECIMALI = "qalc.output.carattereSeparaDecimali";     //DG

……………………..

function carattereSeparaGruppiCifre() {
    return getConfiguration(SEPARA_GRUPPI_CIFRE);
}
exports.carattereSeparaGruppiCifre = carattereSeparaGruppiCifre;

function carattereSeparaDecimali() {
    return getConfiguration(SEPARA_DECIMALI);
}
exports.carattereSeparaDecimali = carattereSeparaDecimali;
```

### document.js
```
carattereSeparaGruppiCifre: settings_1.carattereSeparaGruppiCifre(),   
carattereSeparaDecimali: settings_1.carattereSeparaDecimali() 
```     

### decorator.js
```
carattereSeparaGruppiCifre: settings_1.carattereSeparaGruppiCifre(),  
carattereSeparaDecimali: settings_1.carattereSeparaDecimali() 
```    

### formatter.js
```
//replace the decimal separator with temporary characters
output = output.replace(/\./, '#');

//add the digit group separator
output = output.replace(/\B(?<!\#\d*)(?=(\d{3})+(?!\d))/g, formatterSettings.carattereSeparaGruppiCifre);

//replace the decimal separator
output = output.replace(/\#/, formatterSettings.carattereSeparaDecimali);
```

**Comment by ml-1** [comment]
@nortakales I'm really missing this feature.
Would this be merged if it was made into a pull request or are there any things that needs to be rewritten?

**Comment by nortakales** [comment]
I'll look into it this week. I think it should be fairly straightforward, I just want to make sure I honor existing settings or somehow migrate them to the new settings so I don't change things unexpectedly for existing users.

**Comment by nortakales** [comment]
Added these settings in version 0.3.0

Commit: https://github.com/nortakales/vs-code-qalc/commit/92ad4e6b9df17d4d8911e7b621fa7143726cdc7f
