### ISSUE TITLE
[Feature] Toggle Line Comment

### ISSUE THREAD

**Issue by danilort** [nortakales/vs-code-qalc#15]
I suggest adding the support to the VSCODE command for toggling comments ("Editor.action.commentLine"), which adds or removes line comments, pressing the appropriate key.
https://code.visualstudio.com/api/language-extensions/language-configuration-guide#comment-toggling

# What to change

### create language-configuration.json
```
{
    "comments": {
        // symbol used for single line comment. Remove this entry if your language does not support line comments
        "lineComment": "//",
    }
}
```

### modify package.json
```
"languages": [
    {
        "id": "qalc",
        "aliases": [
            "Qalc"
        ],
        "extensions": [
            ".qalc"
        ],
        "configuration": "./language-configuration.json"
    }
],
```

**Comment by nortakales** [comment]
Added in Qalc 0.1.9
