### ISSUE TITLE
Shift operation error?

### ISSUE THREAD

**Issue by hongshui3000** [nortakales/vs-code-qalc#17]
![image](https://user-images.githubusercontent.com/25566498/153701139-513da7ee-de5b-4dfd-a524-830693cbcd41.png)

should show 0b0? ?

**Comment by nortakales** [comment]
It's a little clunky, but all of these variations seem to work and give a clue to what is going on:

```
bignumber(0b01) << 100       = 1,267,650,600,228,229,401,496,703,205,376
0b01 << bignumber(100)       = 1,267,650,600,228,229,401,496,703,205,376
bin(0b01 << bignumber(100))  = "0b10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
bin(bignumber(0b01) << 100)  = "0b10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
```

Everything here (bin(), 0b01, <<, bignumber()) is handled by Math.js and not specific to this extension, so I don't have a great idea on how to solve this in a better way.
