### ISSUE TITLE
Sum function on a matrix does not work as expected

### ISSUE THREAD

**Issue by oli3012** [nortakales/vs-code-qalc#18]
For example doing sum([1, 2, 3]) gives a result of [37.5, 75, 112.5] depending on previously entered numbers. Probably a mixup with the sum keyword?

**Comment by nortakales** [comment]
Definitely a bug with my custom "sum" keyword which is intended to sum up all previous lines until reaching an empty line. This should be a straightforward fix.

**Comment by nortakales** [comment]
Fixed in Qalc 0.1.9
