### ISSUE TITLE
[Feature] Can you provide an ASCII Table conversion function ?

### ISSUE THREAD

**Issue by hongshui3000** [nortakales/vs-code-qalc#19]
For example, characters can be converted into corresponding hex codes, or hex can be converted into corresponding characters

**Comment by nortakales** [comment]
This will be in v0.1.11

**Comment by nortakales** [comment]
https://github.com/nortakales/vs-code-qalc/commit/2ce73355ca35678700013924c88cbdccbe4e58c6
