### ISSUE TITLE
[Feature] Can I configure filename and filetype filtering

### ISSUE THREAD

**Issue by hongshui3000** [nortakales/vs-code-qalc#20]
I don't want this plugin to execute on files with certain filenames. For example the file config or .config

**Comment by nortakales** [comment]
This will be in v0.1.11. You will be able to supply a list of standard glob patterns for Qalc to ignore.

**Comment by nortakales** [comment]
https://github.com/nortakales/vs-code-qalc/commit/4c3716f8f4ff4390a3f995bb0934e9763d673dc0
