### ISSUE TITLE
[Feature] Add or subtract percentage

### ISSUE THREAD

**Issue by impworks** [nortakales/vs-code-qalc#22]
The following expression is evaluated incorrectly:

```
200 + 10%
```
Expected result: 220
Actual result: 200

Would be nice to have this notation supported, since most physical calculators understand it.

**Comment by nortakales** [comment]
This will be in version v.0.1.11

**Comment by nortakales** [comment]
https://github.com/nortakales/vs-code-qalc/commit/f3591d17ffa924ae88c8a20c918093a552be964e
https://github.com/nortakales/vs-code-qalc/commit/844041d7f1b32d0c2e63ee087282ce540c5ac2a0
