### ISSUE TITLE
Support fahrenheit and celsius shorthand

### ISSUE THREAD

**Issue by misolori** [nortakales/vs-code-qalc#23]
![image](https://user-images.githubusercontent.com/35271042/175351707-24d3a5a1-78dd-4950-bddb-5bfe9e1eae2f.png)

`90 fahrenheit to celsius` is supported but `90 f to c` is not. Would love to make it easier to write out and not misspell 😄

**Comment by nortakales** [comment]
I don't recall why I didn't enable `f` and `c`. I thought they might have overlapped with some other unit, but I'm not seeing what that unit could have been now. I see `F` is used by farad and `C` for coulomb.

I did add support for `oF` and `oC` which you can toggle with a setting. Also note that `degF` and `degC` are supported.

I think adding support for lowercase `c` and `f` makes sense. I'll add it.

**Comment by nortakales** [comment]
This will be available in version  0.1.11

**Comment by nortakales** [comment]
https://github.com/nortakales/vs-code-qalc/commit/0ad15fef8012d77f4c4862d70cce48c60e65170a
