### ISSUE TITLE
Support for value label

### ISSUE THREAD

**Issue by vilicvane** [nortakales/vs-code-qalc#25]
Numi user tries to migrate Qalc here.

I use Numi for personal accounting, usage example:

E.g.:

```
food: 40 + 20 + 40
cloud service: 120
telecom: 100
sum
```

**Comment by luis-c465** [comment]
Not the maintainer, but I looked into how this could be done, and it looks like it would require adding a custom operator to [math.js which means adding it to parse.js as well](https://github.com/josdejong/mathjs/issues/75#issuecomment-23921553)

This might also be possible by using a regex to replace the `:` with a `=` before parsing with math.js

Here's an example of the [regex](https://regex101.com/r/XZsdZx/3)
<img width="287" alt="Screenshot 2023-05-19 at 9 27 03 AM" src="https://github.com/nortakales/vs-code-qalc/assets/80722367/c5f31856-12e0-4423-bf11-9013acea5c39">

**Comment by nortakales** [comment]
You can actually get pretty close to this already like this:
![Screenshot 2023-05-25 204259](https://github.com/nortakales/vs-code-qalc/assets/25379568/2f54a43f-f7b6-4ad9-8d61-e5dce08cfdfb)

Is this close enough?

**Comment by nortakales** [comment]
Closing this issue out since I believe using `=` is comparable to `:` from Numi. If this is an issue (other than a quick re-learning or re-mapping your brain to the different symbol from Numi) feel free to reopen this.
