### ISSUE TITLE
Hex literals containing "c" are not evaluated correctly?

### ISSUE THREAD

**Issue by clnhlzmn** [nortakales/vs-code-qalc#39]
<img width="443" alt="image" src="https://github.com/user-attachments/assets/d08f9531-4854-44f3-9b64-7cb6205e58d6">

I'm not sure what is going on here. Perhaps related to https://github.com/nortakales/vs-code-qalc/issues/23?

Just writing this down for now. I'll try to take a deeper look in a day or two and maybe I can figure out what's up.

**Comment by clnhlzmn** [comment]
Yeah indeed that is the problem. I'm ok with a workaround of disabling the temperature shortcuts for now.

Specifically [this regex](https://github.com/nortakales/vs-code-qalc/commit/0ad15fef8012d77f4c4862d70cce48c60e65170a#diff-df7446068188621a3fa66e02d4e5c9081902f1bb2cd9092e06c59271978257d3R97) appears to match things like these hex literals containing "c", in some cases.

![image](https://github.com/user-attachments/assets/e9791423-fb91-4e0e-b20b-9ab1dc39f2b1)

**Comment by nortakales** [comment]
I think I found a suitable regex replacement. It passes my current tests, and fixes hex strings. We'll see if anyone reports a different issue after the update 😅

**Comment by nortakales** [comment]
Fixed in `0.4.1`

https://github.com/nortakales/vs-code-qalc/commit/59c16cdae7f4ce8f1d7fa3826f14015943056c00
