### ISSUE TITLE
average regex prevents evaluation of some expressions?

### ISSUE THREAD

**Issue by cholzman-rs** [nortakales/vs-code-qalc#40]
I think I found another issue with a regex

<img width="530" alt="image" src="https://github.com/user-attachments/assets/acf54694-9bee-41d9-81b5-828a7620ceb6">

Might be related to [this one](https://github.com/nortakales/vs-code-qalc/blob/59c16cdae7f4ce8f1d7fa3826f14015943056c00/src/document.ts#L171) or the one on the next line?

**Comment by nortakales** [comment]
Fixed in `0.4.2`, should be on the marketplace shortly

https://github.com/nortakales/vs-code-qalc/commit/3f909a7fa538e14a63947ff9d85368998c6b436f
