### ISSUE TITLE
Unsupported on VC Code Server?

### ISSUE THREAD

**Issue by yourfriendaaron** [nortakales/vs-code-qalc#41]
Tried installing this on Code Server and it's not in the extensions store there. Does this need to be local only?

**Comment by nortakales** [comment]
Do you mean vscode.dev? If so we have a feature request open for that here: https://github.com/nortakales/vs-code-qalc/issues/3

**Comment by yourfriendaaron** [comment]
I'm referring to the [selfhosted version](https://github.com/coder/code-server), not sure if that's functionally the same as vscode.dev

**Comment by yourfriendaaron** [comment]
but I was able to install Qalc manually on code-server by installing the .vsix extension directly, so I guess the issue can be closed since there's a workaround, it just didn't show up in the extensions marketplace.
