### ISSUE TITLE
Percentages with variables

### ISSUE THREAD

**Issue by skinneejoe** [nortakales/vs-code-qalc#7]
I don't seem to be able to get percentages working with variables. Maybe this is a known issue. Example:

`total = 500

53% off of total

total                                     =32,639.9

53% off of 500                            =235`

**Comment by skinneejoe** [comment]
![image](https://user-images.githubusercontent.com/7516043/144896471-5e6b40a7-0626-4996-979e-70a53512a140.png)

The text didn't paste very well, I think this attached image will do better.

**Comment by danilort** [comment]
I think the Total name is reserved.
![immagine](https://user-images.githubusercontent.com/16148184/146978100-f24ffe7a-f6a1-49a7-94a4-bcdc5663e925.png)

Try like this:
![immagine](https://user-images.githubusercontent.com/16148184/146978314-bf0cef3d-e4a6-4c42-b478-c4af3cab7920.png)

**Comment by skinneejoe** [comment]
> I think the Total name is reserved. ![immagine](https://user-images.githubusercontent.com/16148184/146978100-f24ffe7a-f6a1-49a7-94a4-bcdc5663e925.png)
> 
> Try like this: ![immagine](https://user-images.githubusercontent.com/16148184/146978314-bf0cef3d-e4a6-4c42-b478-c4af3cab7920.png)

I think the issue is more specifically with the "off of" keyword, see below:
![image](https://user-images.githubusercontent.com/7516043/146980456-9afdcb49-ae8f-4a47-bb43-041e1a3b6d5b.png)

**Comment by nortakales** [comment]
This will be fixed in the next release. In addition, I have fixed a bug where `total = 500` should have been displaying an error message.

**Comment by nortakales** [comment]
Bug fixed in Qalc v0.1.8

**Comment by skinneejoe** [comment]
Awesome, thank you!!
